order:
    resource:
        path: ../src/Order/Controller/
        namespace: App\Order\Controller
    type: attribute
    prefix: /order

printer:
    resource:
        path: ../src/Printer/Controller/
        namespace: App\Printer\Controller
    type: attribute
    prefix: /printer
